<#
.SYNOPSIS
  Search the repo-local compiled context wiki.

.DESCRIPTION
  Reads the search index generated by Build-RepoContextWiki.ps1 and returns
  source-cited matches. If the wiki is missing, this script can build it first
  with -BuildIfMissing.
#>
param(
  [string]$Root = '.',
  [Parameter(Mandatory = $true)][string]$Query,
  [string]$WikiPath,
  [int]$MaxResults = 8,
  [switch]$BuildIfMissing,
  [switch]$Json
)

$ErrorActionPreference = 'Stop'
$scriptDir = $PSScriptRoot
if (-not $scriptDir) { $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path }
if ($Root -eq '.') { $Root = (Resolve-Path (Join-Path $scriptDir '..')).Path }

function Resolve-RepoRoot {
  param([string]$Path)
  $resolved = (Resolve-Path -LiteralPath $Path).Path
  try {
    $top = (& git -C $resolved rev-parse --show-toplevel 2>$null)
    if ($LASTEXITCODE -eq 0 -and $top) { return (Resolve-Path -LiteralPath $top.Trim()).Path }
  } catch { }
  return $resolved
}

function Get-Tokens {
  param([string]$Text)
  return @([regex]::Matches($Text.ToLowerInvariant(), '[a-z0-9][a-z0-9_-]{1,}') | ForEach-Object { $_.Value } | Select-Object -Unique)
}

$repoRoot = Resolve-RepoRoot -Path $Root
if (-not $WikiPath) { $WikiPath = Join-Path $repoRoot '.runtime/context-wiki' }
$indexPath = Join-Path $WikiPath 'index/search-index.json'
if (-not (Test-Path -LiteralPath $indexPath -PathType Leaf)) {
  if ($BuildIfMissing) {
    $builder = Join-Path $scriptDir 'Build-RepoContextWiki.ps1'
    & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $builder -Root $repoRoot -OutputPath $WikiPath -Clean *> $null
  } else {
    Write-Output 'CONTEXT_WIKI_MISSING'
    Write-Output ("Run: powershell.exe -NoProfile -ExecutionPolicy Bypass -File scripts/Build-RepoContextWiki.ps1 -Root `"{0}`"" -f $repoRoot)
    exit 0
  }
}

$searchIndex = Get-Content -LiteralPath $indexPath -Raw -Encoding UTF8 | ConvertFrom-Json
$rows = @($searchIndex.rows)
$queryTokens = Get-Tokens -Text $Query
$matches = foreach ($row in $rows) {
  $score = 0
  $hay = (($row.title, $row.source, $row.category, @($row.keywords), @($row.headings)) -join ' ').ToLowerInvariant()
  foreach ($t in $queryTokens) {
    if ($row.title -and ([string]$row.title).ToLowerInvariant().Contains($t)) { $score += 10 }
    if ($row.source -and ([string]$row.source).ToLowerInvariant().Contains($t)) { $score += 6 }
    if (@($row.keywords) -contains $t) { $score += 5 }
    if ($hay.Contains($t)) { $score += 1 }
  }
  if ($score -gt 0) {
    [pscustomobject]@{
      score = $score
      title = $row.title
      source = $row.source
      wikiPath = $row.wikiPath
      category = $row.category
      keywords = @($row.keywords | Select-Object -First 8)
    }
  }
}

$ranked = @($matches | Sort-Object @{ Expression = 'score'; Descending = $true }, @{ Expression = 'title'; Ascending = $true } | Select-Object -First $MaxResults)
if ($Json) {
  [pscustomobject]@{
    status = if ($ranked.Count -gt 0) { 'MATCH' } else { 'NO_MATCH' }
    query = $Query
    wikiPath = $WikiPath
    results = $ranked
  } | ConvertTo-Json -Depth 8
  exit 0
}

if ($ranked.Count -eq 0) {
  Write-Output 'CONTEXT_WIKI_NO_MATCH'
  exit 0
}

Write-Output 'CONTEXT_WIKI_MATCH'
foreach ($r in $ranked) {
  Write-Output ("score={0} source={1} wiki={2} title={3}" -f $r.score, $r.source, $r.wikiPath, $r.title)
}
